!--------------------------------------------------------------------
! сяпедмемхе онкнфемхъ аюккюярмнцн якнъ
!--------------------------------------------------------------------
SUBROUTINE MIDL_UGLUB()
USE PARAM_
USE PARAM_1
USE RAILWAY
IMPLICIT NONE
INTEGER*4  I

R_BALL_UP(N_CHEN_TEK)=(II_BAL(N_CHEN_TEK)-J_LEVEL)*RABTIME			! II_BAL
R_BALL(N_CHEN_TEK)=(II_OSN(N_CHEN_TEK)-J_LEVEL)*RABTIME			! II_BAL

IF(ITEK.GE.N_MIDL_BALL) THEN
	DO I=1,N_MIDL_BALL-1						    	! янупюмъел б люяяхб						
	BALL(N_CHEN_TEK,I)=BALL(N_CHEN_TEK,I+1)
	BALL_UP(N_CHEN_TEK,I)=BALL_UP(N_CHEN_TEK,I+1)
	END DO
	BALL(N_CHEN_TEK,N_MIDL_BALL)=R_BALL(N_CHEN_TEK)
	BALL_UP(N_CHEN_TEK,N_MIDL_BALL)=R_BALL_UP(N_CHEN_TEK)
	R_BALL_MIDL(N_CHEN_TEK)=0.
	R_BALL_MIDL_UP(N_CHEN_TEK)=0.
	DO I=1,N_MIDL_BALL
	R_BALL_MIDL(N_CHEN_TEK)=R_BALL_MIDL(N_CHEN_TEK)+BALL(N_CHEN_TEK,I)
	R_BALL_MIDL_UP(N_CHEN_TEK)=R_BALL_MIDL_UP(N_CHEN_TEK)+BALL_UP(N_CHEN_TEK,I)
	END DO
	R_BALL_MIDL(N_CHEN_TEK)=R_BALL_MIDL(N_CHEN_TEK)/N_MIDL_BALL	! сяпедмъел
	R_BALL_MIDL_UP(N_CHEN_TEK)=R_BALL_MIDL_UP(N_CHEN_TEK)/N_MIDL_BALL	! сяпедмъел
ELSE
	BALL(N_CHEN_TEK,ITEK)=R_BALL(N_CHEN_TEK)							! янупюмъел б люяяхб
	BALL_UP(N_CHEN_TEK,ITEK)=R_BALL_UP(N_CHEN_TEK)							! янупюмъел б люяяхб
	R_BALL_MIDL(N_CHEN_TEK)=0.
	R_BALL_MIDL_UP(N_CHEN_TEK)=0.
	DO I=1,ITEK
	R_BALL_MIDL(N_CHEN_TEK)=R_BALL_MIDL(N_CHEN_TEK)+BALL(N_CHEN_TEK,I)
	R_BALL_MIDL_UP(N_CHEN_TEK)=R_BALL_MIDL_UP(N_CHEN_TEK)+BALL_UP(N_CHEN_TEK,I)
	END DO
	R_BALL_MIDL(N_CHEN_TEK)=R_BALL_MIDL(N_CHEN_TEK)/ITEK		! сяпедмъел
	R_BALL_MIDL_UP(N_CHEN_TEK)=R_BALL_MIDL_UP(N_CHEN_TEK)/ITEK		! сяпедмъел
END IF
777	RETURN
	END