SUBROUTINE MIDLE(N_CHEN_TEK,N_CHEN,RDM,BUFF,L_REGION,M2_REGION,J_LEVEL,N,ITEK)
REAL*4 BUFF(N_CHEN,N,L_REGION)
REAL*4 RAB
INTEGER*4  L_REGION
INTEGER*4  M2_REGION
INTEGER*4  J_LEVEL
INTEGER*4  N
REAL*4 RDM(N)
INTEGER*4  ITEK
INTEGER*4  L1,I,K1,K2,II

	IF(ITEK.LT.L_REGION) THEN
		L1=1; L2=ITEK
	ELSE
		L1=1; L2=L_REGION
    END IF
    
DO I=J_LEVEL,N  ! 秩仕 我 论列劳臀梦 有温瓦
	K1=I-M2_REGION
	K2=I+M2_REGION
	IF(K1.LT.J_LEVEL)K1=J_LEVEL
	IF(K2.GT.N)K2=N
	RAB=0.
	II=0
		DO L=L1,L2
			DO J=K1,K2
			II=II+1
			RAB=RAB+BUFF(N_CHEN_TEK,J,L)
			END DO
		END DO
	RDM(I)=RAB/II
END DO

END SUBROUTINE MIDLE