SUBROUTINE UTF8(DEVICE,MyData,J_START,N)
IMPLICIT NONE
CHARACTER *200 DEVICE
INTEGER*4  J_START,N
CHARACTER(1) :: MyData(*)
CHARACTER (1) STR,STR1,STR2
INTEGER*4  I,II
INTEGER*4  I1,I2,I3

II=1
I=0
1 I=I+1
!READ(MyData(J_START+I-1:J_START+I-1),*)STR
I1=ICHAR(MyData(J_START+I-1))
IF(I1.LT.128) THEN
DEVICE(II:II)=TRANSFER(I1,DEVICE); GOTO 2
END IF

	IF(I1.EQ.208) THEN
	I=I+1; I2=ICHAR(MyData(J_START+I-1))
	IF(I2.EQ.129) THEN
	STR1='®';DEVICE(II:II)=STR1; GOTO 2
	END IF  
	IF(I2.EQ.130)THEN 
	STR1='Ä';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.131)THEN 
	STR1='Å';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.132)THEN 
	STR1='™';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.133)THEN 
	STR1='Ω';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.134)THEN 
	STR1='≤';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.135)THEN 
	STR1='Ø';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.136)THEN 
	STR1='£';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.137)THEN 
	STR1='ä';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.138)THEN 
	STR1='å';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.139)THEN 
	STR1='é';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.140)THEN 
	STR1='ç';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.142)THEN 
	STR1='°';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.143)THEN 
	STR1='è';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.144)THEN 
	STR1='¿';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.145)THEN 
	STR1='¡';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.146)THEN 
	STR1='¬';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.147)THEN 
	STR1='√';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.148)THEN 
	STR1='ƒ';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.149)THEN 
	STR1='≈';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.150)THEN 
	STR1='∆';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.151)THEN 
	STR1='«';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.152)THEN 
	STR1='»';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.153)THEN 
	STR1='…';DEVICE(II:II)=STR1; GOTO 2
	END IF  
	IF(I2.EQ.154)THEN 
	STR1=' ';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.155)THEN 
	STR1='À';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.156)THEN 
	STR1='Ã';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.157)THEN 
	STR1='Õ';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.158)THEN 
	STR1='Œ';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.159)THEN 
	STR1='œ';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.160)THEN 
	STR1='–';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.161)THEN 
	STR1='—';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.162)THEN 
	STR1='“';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.163)THEN 
	STR1='”';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.164)THEN 
	STR1='‘';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.165)THEN 
	STR1='’';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.166)THEN 
	STR1='÷';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.167)THEN 
	STR1='◊';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.168)THEN 
	STR1='ÿ';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.169)THEN 
	STR1='Ÿ';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.170)THEN 
	STR1='⁄';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.171)THEN 
	STR1='€';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.172)THEN 
	STR1='‹';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.173)THEN 
	STR1='›';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.174)THEN 
	STR1='ﬁ';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.175)THEN 
	STR1='ﬂ';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.176)THEN 
	STR1='‡';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.177)THEN 
	STR1='·';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.178)THEN 
	STR1='‚';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.179)THEN 
	STR1='„';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.180)THEN 
	STR1='‰';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.181)THEN 
	STR1='Â';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.182)THEN 
	STR1='Ê';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.183)THEN 
	STR1='Á';DEVICE(II:II)=STR1; GOTO 2
	END IF  
	IF(I2.EQ.184)THEN 
	STR1='Ë';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.185)THEN 
	STR1='È';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.186)THEN 
	STR1='Í';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.187)THEN 
	STR1='Î';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.188)THEN 
	STR1='Ï';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.189)THEN 
	STR1='Ì';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.190)THEN 
	STR1='Ó';DEVICE(II:II)=STR1; GOTO 2
	END IF   
	IF(I2.EQ.191)THEN 
	STR1='Ô';DEVICE(II:II)=STR1; GOTO 2
	END IF 
	STR1='X';DEVICE(II:II)=STR1; GOTO 2	  
	END IF

		IF(I1.EQ.209) THEN
	    I=I+1; I2=ICHAR(MyData(J_START+I-1))
		IF(I2.EQ.128) THEN
		STR1='';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.129) THEN
		STR1='Ò';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.130) THEN
		STR1='Ú';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.131) THEN
		STR1='Û';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.132) THEN
		STR1='Ù';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.133) THEN
		STR1='ı';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.134) THEN
		STR1='ˆ';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.135) THEN
		STR1='˜';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.136) THEN
		STR1='¯';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.137) THEN
		STR1='˘';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.138) THEN
		STR1='˙';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.139) THEN
		STR1='˚';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.140) THEN
		STR1='¸';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.141) THEN
		STR1='˝';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.142) THEN
		STR1='˛';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.143) THEN
		STR1='ˇ';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.145) THEN
		STR1='∏';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.146) THEN
		STR1='ê';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.147) THEN
		STR1='É';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.148) THEN
		STR1='∫';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.149) THEN
		STR1='æ';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.150) THEN
		STR1='≥';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.151) THEN
		STR1='ø';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.152) THEN
		STR1='º';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.153) THEN
		STR1='ö';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.154) THEN
		STR1='ú';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.155) THEN
		STR1='û';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.156) THEN
		STR1='ù';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.158) THEN
		STR1='¢';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		IF(I2.EQ.159) THEN
		STR1='ü';DEVICE(II:II)=STR1; GOTO 2
		END IF 
		STR1='X';DEVICE(II:II)=STR1; GOTO 2	  
		END IF

			IF(I1.EQ.195) THEN
	        I=I+1; I2=ICHAR(MyData(J_START+I-1))
			IF(I2.EQ.160) THEN
			STR1=' ';DEVICE(II:II)=STR1; GOTO 2
			END IF
			IF(I2.EQ.164) THEN
			STR1='§';DEVICE(II:II)=STR1; GOTO 2
			END IF
			IF(I2.EQ.166) THEN
			STR1='¶';DEVICE(II:II)=STR1; GOTO 2
			END IF
			IF(I2.EQ.167) THEN
			STR1='ß';DEVICE(II:II)=STR1; GOTO 2
			END IF
			IF(I2.EQ.169) THEN
			STR1='©';DEVICE(II:II)=STR1; GOTO 2
			END IF
			IF(I2.EQ.171) THEN
			STR1='´';DEVICE(II:II)=STR1; GOTO 2
			END IF
			IF(I2.EQ.172) THEN
			STR1='¨';DEVICE(II:II)=STR1; GOTO 2
			END IF
			IF(I2.EQ.173) THEN
			STR1='≠';DEVICE(II:II)=STR1; GOTO 2
			END IF
			IF(I2.EQ.174) THEN
			STR1='Æ';DEVICE(II:II)=STR1; GOTO 2
			END IF
			IF(I2.EQ.176) THEN
			STR1='∞';DEVICE(II:II)=STR1; GOTO 2
			END IF
			IF(I2.EQ.177) THEN
			STR1='±';DEVICE(II:II)=STR1; GOTO 2
			END IF
			IF(I2.EQ.181) THEN
			STR1='µ';DEVICE(II:II)=STR1; GOTO 2
			END IF
			IF(I2.EQ.182) THEN
			STR1='∂';DEVICE(II:II)=STR1; GOTO 2
			END IF
			IF(I2.EQ.183) THEN
			STR1='∑';DEVICE(II:II)=STR1; GOTO 2
			END IF
			IF(I2.EQ.187) THEN
			STR1='ª';DEVICE(II:II)=STR1; GOTO 2
			END IF
			STR1='X';DEVICE(II:II)=STR1; GOTO 2	  
			END IF

				IF(I1.EQ.195) THEN
	            I=I+1; I2=ICHAR(MyData(J_START+I-1))
				IF(I2.EQ.144) THEN
				STR1='•';DEVICE(II:II)=STR1; GOTO 2
				END IF				
				IF(I2.EQ.145) THEN
				STR1='¥';DEVICE(II:II)=STR1; GOTO 2
				END IF				
				STR1='X';DEVICE(II:II)=STR1; GOTO 2	  
				END IF

					IF(I1.EQ.226) THEN
	                I=I+1; I2=ICHAR(MyData(J_START+I-1))
					IF(I2.EQ.128) THEN
					I=I+1;I3=ICHAR(MyData(J_START+I-1))
					IF(I3.EQ.154) THEN
					STR2='Ç';DEVICE(II:II)=STR2; GOTO 2
					END IF					
					IF(I3.EQ.158) THEN
					STR2='Ñ';DEVICE(II:II)=STR2; GOTO 2
					END IF				
					IF(I3.EQ.160) THEN
					STR2='Ü';DEVICE(II:II)=STR2; GOTO 2
					END IF
					IF(I3.EQ.161) THEN
					STR2='á';DEVICE(II:II)=STR2; GOTO 2
					END IF				
					IF(I3.EQ.166) THEN
					STR2='Ö';DEVICE(II:II)=STR2; GOTO 2
					END IF				
					IF(I3.EQ.176) THEN
					STR2='â';DEVICE(II:II)=STR2; GOTO 2
					END IF				
					IF(I3.EQ.185) THEN
					STR2='ã';DEVICE(II:II)=STR2; GOTO 2
					END IF				
					IF(I3.EQ.152) THEN
					STR2='ë';DEVICE(II:II)=STR2; GOTO 2
					END IF				
					IF(I3.EQ.153) THEN
					STR2='í';DEVICE(II:II)=STR2; GOTO 2
					END IF				
					IF(I3.EQ.156) THEN
					STR2='ì';DEVICE(II:II)=STR2; GOTO 2
					END IF				
					IF(I3.EQ.157) THEN
					STR2='î';DEVICE(II:II)=STR2; GOTO 2
					END IF				
					IF(I3.EQ.162) THEN
					STR2='ï';DEVICE(II:II)=STR2; GOTO 2
					END IF				
					IF(I3.EQ.147) THEN
					STR2='ñ';DEVICE(II:II)=STR2; GOTO 2
					END IF				
					IF(I3.EQ.148) THEN
					STR2='ó';DEVICE(II:II)=STR2; GOTO 2
					END IF				
					IF(I3.EQ.186) THEN
					STR2='õ';DEVICE(II:II)=STR2; GOTO 2
					END IF					
					STR2='X';DEVICE(II:II)=STR2; GOTO 2	  
					END IF
					END IF

				IF(I1.EQ.226) THEN
                I=I+1; I2=ICHAR(MyData(J_START+I-1))
				IF(I2.EQ.130) THEN
                I=I+1; I3=ICHAR(MyData(J_START+I-1))
				IF(I3.EQ.172) THEN
				STR2='à';DEVICE(II:II)=STR2; GOTO 2
				END IF					
				STR2='X';DEVICE(II:II)=STR2; GOTO 2	  
				END IF
				END IF								
			IF(I1.EQ.239) THEN
            I=I+1; I2=ICHAR(MyData(J_START+I-1))
			IF(I2.EQ.191) THEN
            I=I+1; I3=ICHAR(MyData(J_START+I-1))
			IF(I3.EQ.189) THEN
			STR2='?';DEVICE(II:II)=STR2; GOTO 2
			END IF					
			STR2='X';DEVICE(II:II)=STR2; GOTO 2	  
			END IF
			END IF
		IF(I1.EQ.226) THEN
        I=I+1; I2=ICHAR(MyData(J_START+I-1))
		IF(I2.EQ.132) THEN
        I=I+1; I3=ICHAR(MyData(J_START+I-1))
		IF(I3.EQ.150) THEN
		STR2='π';DEVICE(II:II)=STR2; GOTO 2
		END IF			
		IF(I3.EQ.162) THEN
		STR2='ô';DEVICE(II:II)=STR2; GOTO 2
		END IF			
		IF(I3.EQ.189) THEN
		STR2='?';DEVICE(II:II)=STR2; GOTO 2
		END IF					
		STR2='X';DEVICE(II:II)=STR2; GOTO 2	  
		END IF
		END IF
DEVICE(II:II)='X'
2 II=II+1
IF(I.LT.N) GOTO 1
RETURN
END SUBROUTINE UTF8

!open(unit=100, FILE='D:/OUTPUT.OUT')
!write(100,*)