SUBROUTINE GEOSCAN_INPUT()
USE GEOSCANINPUT
USE GEOSKANGLOBALS
IMPLICIT NONE
EXTERNAL WHAT_GEOINPUT
FLAG=DLGINIT(DIALOG2,D_2)					! инициализация диалога
FLAG=DLGSETSUB(D_2,DEVICE,WHAT_GEOINPUT)			    ! 
FLAG=DLGSETSUB(D_2,VAY,WHAT_GEOINPUT)			        ! 
FLAG=DLGSETSUB(D_2,DIRECTION,WHAT_GEOINPUT)			    ! 
FLAG=DLGSETSUB(D_2,TRAK,WHAT_GEOINPUT)			        ! 
FLAG=DLGSETSUB(D_2,YES,WHAT_GEOINPUT)			        ! 
FLAG=DLGSETSUB(D_2,NO,WHAT_GEOINPUT)			        ! 

N_DEVICE(1:50)=   'Аппаратура_РГУПС                                  '
N_VAY(1:50)=      'СКЖД                                              '
N_DIRECTION(1:50)='Туапсе-Адлер                                    '
N_TRACK(1:50)=    '1                                                 '

FLAG=DLGSET(D_2,DEVICE,ADJUSTL(N_DEVICE))			    ! 
FLAG=DLGSET(D_2,VAY,ADJUSTL(N_VAY))			        ! 
FLAG=DLGSET(D_2,DIRECTION,ADJUSTL(N_DIRECTION))			! 
FLAG=DLGSET(D_2,TRACK,ADJUSTL(N_TRACK))			        ! 

STATUS=DLGMODAL(D_2)							! отображение диалога
RETURN
END SUBROUTINE GEOSCAN_INPUT 

    

SUBROUTINE WHAT_GEOINPUT(FILE_DLG,C_MAME,CBTYPE)
USE GEOSCANINPUT
USE GEOSKANGLOBALS
!USE PARAM_1
IMPLICIT NONE
TYPE(DIALOG) FILE_DLG
INTEGER(4) C_MAME,CBTYPE
INTEGER(4) I
INTEGER*4 IRESULTAT     ! ПАРАМЕТР ОШИБКИ ПРИ ВЫПОЛНЕНИИ ПРОЦЕДУРЫ GEOSKANGLOBALS=0
I=CBTYPE						! БЛОКИРОВКА ТРАНСЛЯТОРА
SELECT CASE(C_MAME)

CASE(YES)
    FLAG=DLGGET(FILE_DLG,DEVICE,N_DEVICE)
    FLAG=DLGGET(FILE_DLG,VAY,N_VAY)
    FLAG=DLGGET(FILE_DLG,DIRECTION,N_DIRECTION)
    FLAG=DLGGET(FILE_DLG,TRACK,N_TRACK)
    N_DEVICE=TRIM(N_DEVICE)
    N_VAY=TRIM(N_VAY)
    N_DIRECTION=TRIM(N_DIRECTION)
    N_TRACK=TRIM(N_TRACK)
	CALL DLGEXIT(FILE_DLG)		! ЗАКРЫВАЕМ ДИАЛОГ
CASE(NO)
	CALL DLGEXIT(FILE_DLG)		! ЗАКРЫВАЕМ ДИАЛОГ
END SELECT
    END SUBROUTINE 	WHAT_GEOINPUT
    
